version: "3.9"

services:
  app:
    build:
      context: .
      target: builder
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - REMOTE_SERVER_URL=${REMOTE_SERVER_URL}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - KUBERNETES_API_USERNAME=${KUBERNETES_API_USERNAME}
      - KUBERNETES_API_PASSWORD=${KUBERNETES_API_PASSWORD}
      - KUBECONFIG_PATH=${KUBECONFIG_PATH}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SCHEDULER_RECOMMEND_APPLICATION_SCALING_IN_SECONDS=${SCHEDULER_RECOMMEND_APPLICATION_SCALING_IN_SECONDS}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - ACCEPTED_USAGE_PERCENTAGE=80