version: "3.9"

services:
  app:
    build:
      context: .
      target: builder
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SCHEDULER_RECOMMEND_APPLICATION_SCALING_IN_SECONDS=${SCHEDULER_RECOMMEND_APPLICATION_SCALING_IN_SECONDS}
      - SCHEDULER_SCALE_APPLICATION_AND_NOTIFY_IN_SECONDS=${SCHEDULER_SCALE_APPLICATION_AND_NOTIFY_IN_SECONDS}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - MAIL_JET_API_KEY=${MAIL_JET_API_KEY}
      - MAIL_JET_SECRET_KEY=${MAIL_JET_SECRET_KEY}
      - PRIVATE_HARBOR_REGISTRY_URL=${PRIVATE_HARBOR_REGISTRY_URL}
      - PRIVATE_HARBOR_REGISTRY_USERNAME=${PRIVATE_HARBOR_REGISTRY_USERNAME}
      - PRIVATE_HARBOR_REGISTRY_PASSWORD=${PRIVATE_HARBOR_REGISTRY_PASSWORD}
      - KUBECONFIG_CONTENT=${KUBECONFIG_CONTENT}